"""
report_generator.py — Markdown + PDF audit reports.
PDF: fixed cover layout, per-page footer with Digital Solution branding.
"""

import os
from datetime import datetime
from typing import Dict, List, Optional

from utils import ensure_dir, get_timestamp

LINKEDIN_URL   = "linkedin.com/in/jawad-hussain-digital-solution/"
BRAND_NAME     = "Digital Solution  |  Jawad Hussain"
CONTACT_EMAIL  = "jawadweb79@gmail.com"


# ── Markdown ────────────────────────────────────────────────────────────────────

def generate_markdown_report(analysis: Dict, roi: Dict, ai_content: Dict) -> str:
    workflow   = analysis["input"]
    classified = analysis["classified_tasks"]
    inefficiencies = analysis["inefficiencies"]
    timestamp  = datetime.now().strftime("%d %B %Y, %H:%M")
    ai_note    = "AI-powered (DeepSeek)" if ai_content.get("success") else "Deterministic fallback"

    lines: List[str] = []
    lines += [
        "# AI Workflow Audit Report", "",
        f"| Field | Value |",
        f"|-------|-------|",
        f"| **Generated** | {timestamp} |",
        f"| **Role** | {workflow['role']} |",
        f"| **Industry** | {workflow['industry']} |",
        f"| **AI Layer** | {ai_note} |",
        "", "---", "",
    ]

    lines += [
        "## SECTION 1 — CURRENT WORKFLOW", "",
        f"**Total weekly hours:** {analysis['total_weekly_hours']:.1f}h  ",
        f"**Tools:** {', '.join(workflow['tools_used']) or 'None'}  ",
        f"**Pain points:** {', '.join(workflow['pain_points']) or 'None'}",
        "", "| # | Task | Hours/Week | Category | Reducible |",
        "|---|------|-----------|----------|-----------|",
    ]
    for i, ct in enumerate(classified, 1):
        badge = {"repetitive":"🔁","creative":"🎨","operational":"⚙️","decision-based":"🧠"}.get(ct["category"],"")
        lines.append(f"| {i} | {ct['task']} | {ct['hours']:.1f}h | {badge} {ct['category']} | {ct['reduction_factor']*100:.0f}% |")
    lines.append("")

    lines += ["## SECTION 2 — KEY INEFFICIENCIES", ""]
    if inefficiencies:
        for item in inefficiencies:
            badge = {"HIGH":"🔴 HIGH","MEDIUM":"🟡 MEDIUM","LOW":"🟢 LOW"}.get(item["severity"], item["severity"])
            lines += [f"### {badge} — {item['task']}",
                      f"**Reason:** {item['reason']}  ",
                      f"**Impact:** {item['impact']}", ""]
    else:
        lines += ["*No major inefficiencies detected.*", ""]
    lines += ["---", ""]

    lines += [ai_content["content"].strip(), "", "---", ""]

    lines += [
        "## SECTION 6 — ROI ESTIMATION", "",
        "| Metric | Value |", "|--------|-------|",
        f"| Time saved per week | **{roi['time_saved_per_week']:.1f} hours** |",
        f"| Efficiency improvement | **{roi['efficiency_gain_percent']}%** |",
        f"| Automation score | **{roi['automation_score']} / 100** |",
        f"| Annual hours saved | **{roi['annual_hours_saved']:.0f} hours** |",
        f"| Annual value (@ ${roi['hourly_value_used']:.0f}/hr) | **${roi['annual_value_usd']:,.0f}** |",
        "", "### Breakdown by Category", "",
        "| Category | Tasks | Current h/week | Hours Saved |",
        "|----------|-------|---------------|-------------|",
    ]
    for cat, data in roi["category_breakdown"].items():
        lines.append(f"| `{cat}` | {data['tasks']} | {data['total_hours']:.1f}h | **{data['hours_saved']:.1f}h** |")
    lines += [
        "", "---", "",
        f"*Generated by **AI Workflow Auditor** — {BRAND_NAME}*  ",
        f"*{LINKEDIN_URL}  ·  {CONTACT_EMAIL}*", "",
    ]
    return "\n".join(lines)


def save_markdown(content: str, output_dir: str, filename: str) -> str:
    ensure_dir(output_dir)
    filepath = os.path.join(output_dir, filename)
    with open(filepath, "w", encoding="utf-8") as f:
        f.write(content)
    return filepath


# ── PDF ─────────────────────────────────────────────────────────────────────────

def save_pdf(analysis: Dict, roi: Dict, ai_content: Dict, output_dir: str, filename: str) -> Optional[str]:
    try:
        from reportlab.lib.pagesizes import A4
        from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
        from reportlab.lib.units import cm
        from reportlab.lib.colors import HexColor
        from reportlab.platypus import (
            SimpleDocTemplate, Paragraph, Spacer, Table,
            TableStyle, HRFlowable, KeepTogether,
        )
        from reportlab.lib.enums import TA_LEFT, TA_CENTER
        from reportlab.lib import colors
        from reportlab.pdfgen import canvas as rl_canvas
    except ImportError:
        return None

    ensure_dir(output_dir)
    filepath = os.path.join(output_dir, filename)

    PAGE_W, PAGE_H = A4
    L_MARGIN = 2.2 * cm
    R_MARGIN = 2.2 * cm
    T_MARGIN = 2.2 * cm
    B_MARGIN = 2.2 * cm   # footer sits at ~1.4 cm

    C_DARK   = HexColor("#0f172a")
    C_BLUE   = HexColor("#1e40af")
    C_ACCENT = HexColor("#3b82f6")
    C_LIGHT  = HexColor("#f1f5f9")
    C_BORDER = HexColor("#cbd5e1")
    C_RED    = HexColor("#dc2626")
    C_YELLOW = HexColor("#d97706")
    C_GREEN  = HexColor("#16a34a")
    C_TEXT   = HexColor("#1e293b")
    C_MUTED  = HexColor("#64748b")

    workflow       = analysis["input"]
    classified     = analysis["classified_tasks"]
    inefficiencies = analysis["inefficiencies"]

    # ── Footer drawn on every page ────────────────────────────────────────────
    def draw_footer(canv, doc):
        canv.saveState()
        y = 1.3 * cm
        # separator line
        canv.setStrokeColor(C_BORDER)
        canv.setLineWidth(0.4)
        canv.line(L_MARGIN, y + 0.35 * cm, PAGE_W - R_MARGIN, y + 0.35 * cm)
        # left — brand
        canv.setFont("Helvetica-Bold", 7.5)
        canv.setFillColor(C_BLUE)
        canv.drawString(L_MARGIN, y, BRAND_NAME)
        # centre — page number
        canv.setFont("Helvetica", 7.5)
        canv.setFillColor(C_MUTED)
        canv.drawCentredString(PAGE_W / 2, y, f"Page {canv.getPageNumber()}")
        # right — LinkedIn
        canv.setFont("Helvetica", 7)
        canv.setFillColor(C_ACCENT)
        canv.drawRightString(PAGE_W - R_MARGIN, y, LINKEDIN_URL)
        canv.restoreState()

    doc = SimpleDocTemplate(
        filepath,
        pagesize=A4,
        leftMargin=L_MARGIN, rightMargin=R_MARGIN,
        topMargin=T_MARGIN,  bottomMargin=B_MARGIN,
        title="AI Workflow Audit Report",
        author=BRAND_NAME,
    )

    base = getSampleStyleSheet()
    def S(name, **kw):
        return ParagraphStyle(name, parent=base["Normal"], **kw)

    styles = {
        "title":   S("Title",   fontSize=24, textColor=C_DARK,   spaceAfter=10, spaceBefore=0, alignment=TA_CENTER, fontName="Helvetica-Bold"),
        "sub":     S("Sub",     fontSize=10, textColor=C_MUTED,  spaceAfter=14, alignment=TA_CENTER),
        "h1":      S("H1",      fontSize=13, textColor=C_BLUE,   spaceBefore=16, spaceAfter=8,  fontName="Helvetica-Bold"),
        "h2":      S("H2",      fontSize=10, textColor=C_DARK,   spaceBefore=8,  spaceAfter=4,  fontName="Helvetica-Bold"),
        "body":    S("Body",    fontSize=9,  textColor=C_TEXT,   leading=14,    spaceAfter=4),
        "bullet":  S("Bullet",  fontSize=9,  textColor=C_TEXT,   leading=13,    leftIndent=14, spaceAfter=3),
        "caption": S("Caption", fontSize=7.5,textColor=C_MUTED,  spaceAfter=8),
        "footer_brand": S("FooterBrand", fontSize=8, textColor=C_BLUE, fontName="Helvetica-Bold"),
    }

    story = []
    CONTENT_W = PAGE_W - L_MARGIN - R_MARGIN

    def hr():
        story.append(Spacer(1, 0.25*cm))
        story.append(HRFlowable(width="100%", thickness=0.4, color=C_BORDER))
        story.append(Spacer(1, 0.25*cm))

    def h1(text):
        story.append(Paragraph(text, styles["h1"]))

    def body(text):
        t = text.replace("**","").replace("*","").replace("`","")
        story.append(Paragraph(t, styles["body"]))

    def bullet(text):
        t = text.lstrip("-•* ").replace("**","").replace("`","")
        story.append(Paragraph(f"• {t}", styles["bullet"]))

    # ── Cover ─────────────────────────────────────────────────────────────────
    story.append(Spacer(1, 1.0 * cm))
    story.append(Paragraph("AI Workflow Audit Report", styles["title"]))
    story.append(Spacer(1, 0.3 * cm))
    story.append(Paragraph(
        f"{workflow['role']}  ·  {workflow['industry']}  ·  "
        f"{datetime.now().strftime('%d %B %Y')}",
        styles["sub"],
    ))
    hr()

    # ── Metadata table ────────────────────────────────────────────────────────
    meta_rows = [
        ["Role",             workflow["role"]],
        ["Industry",         workflow["industry"]],
        ["Tools",            ", ".join(workflow["tools_used"]) or "None"],
        ["Pain Points",      ", ".join(workflow["pain_points"]) or "None"],
        ["Total Hours/Week", f"{analysis['total_weekly_hours']:.1f}h"],
        ["AI Layer",         "DeepSeek AI" if ai_content.get("success") else "Deterministic Fallback"],
    ]
    meta_t = Table(meta_rows, colWidths=[4*cm, CONTENT_W - 4*cm])
    meta_t.setStyle(TableStyle([
        ("BACKGROUND",    (0,0),(0,-1), C_LIGHT),
        ("TEXTCOLOR",     (0,0),(0,-1), C_BLUE),
        ("FONTNAME",      (0,0),(0,-1), "Helvetica-Bold"),
        ("FONTSIZE",      (0,0),(-1,-1), 9),
        ("GRID",          (0,0),(-1,-1), 0.3, C_BORDER),
        ("ROWBACKGROUNDS",(0,0),(-1,-1), [colors.white, C_LIGHT]),
        ("VALIGN",        (0,0),(-1,-1), "MIDDLE"),
        ("TOPPADDING",    (0,0),(-1,-1), 5),
        ("BOTTOMPADDING", (0,0),(-1,-1), 5),
        ("LEFTPADDING",   (0,0),(-1,-1), 8),
    ]))
    story.append(meta_t)
    story.append(Spacer(1, 0.4*cm))

    # ── Section 1 ─────────────────────────────────────────────────────────────
    h1("SECTION 1 — CURRENT WORKFLOW")
    task_hdr = [["#", "Task", "h/wk", "Category", "Reducible"]]
    task_rows = [
        [str(i+1), ct["task"], f"{ct['hours']:.1f}h",
         ct["category"], f"{ct['reduction_factor']*100:.0f}%"]
        for i, ct in enumerate(classified)
    ]
    col_w = [0.8*cm, CONTENT_W - 9.3*cm, 1.8*cm, 4*cm, 2.5*cm]
    task_t = Table(task_hdr + task_rows, colWidths=col_w)
    task_t.setStyle(TableStyle([
        ("BACKGROUND",    (0,0),(-1,0), C_BLUE),
        ("TEXTCOLOR",     (0,0),(-1,0), colors.white),
        ("FONTNAME",      (0,0),(-1,0), "Helvetica-Bold"),
        ("FONTSIZE",      (0,0),(-1,-1), 8.5),
        ("GRID",          (0,0),(-1,-1), 0.3, C_BORDER),
        ("ROWBACKGROUNDS",(0,1),(-1,-1), [colors.white, C_LIGHT]),
        ("VALIGN",        (0,0),(-1,-1), "MIDDLE"),
        ("TOPPADDING",    (0,0),(-1,-1), 5),
        ("BOTTOMPADDING", (0,0),(-1,-1), 5),
        ("LEFTPADDING",   (0,0),(-1,-1), 6),
        ("WORDWRAP",      (1,0),(1,-1), True),
    ]))
    story.append(task_t)
    story.append(Spacer(1, 0.3*cm))

    # ── Section 2 ─────────────────────────────────────────────────────────────
    hr()
    h1("SECTION 2 — KEY INEFFICIENCIES")
    if inefficiencies:
        for item in inefficiencies:
            sev_col = {"HIGH": C_RED, "MEDIUM": C_YELLOW, "LOW": C_GREEN}.get(item["severity"], C_MUTED)
            badge_t = Table([[f"[{item['severity']}]  {item['task']}"]], colWidths=[CONTENT_W])
            badge_t.setStyle(TableStyle([
                ("BACKGROUND",    (0,0),(-1,-1), sev_col),
                ("TEXTCOLOR",     (0,0),(-1,-1), colors.white),
                ("FONTNAME",      (0,0),(-1,-1), "Helvetica-Bold"),
                ("FONTSIZE",      (0,0),(-1,-1), 9),
                ("TOPPADDING",    (0,0),(-1,-1), 5),
                ("BOTTOMPADDING", (0,0),(-1,-1), 5),
                ("LEFTPADDING",   (0,0),(-1,-1), 10),
                ("ROUNDEDCORNERS",(0,0),(-1,-1), [4,4,4,4]),
            ]))
            story.append(KeepTogether([
                badge_t,
                Spacer(1, 0.1*cm),
                Paragraph(f"<b>Reason:</b> {item['reason']}", styles["body"]),
                Paragraph(f"<b>Impact:</b> {item['impact']}", styles["body"]),
                Spacer(1, 0.2*cm),
            ]))
    else:
        body("No major inefficiencies detected by the rule engine.")

    # ── Sections 3, 4, 5, 7 — AI ─────────────────────────────────────────────
    hr()
    for line in ai_content["content"].strip().split("\n"):
        s = line.strip()
        if not s or s == "---":
            story.append(Spacer(1, 0.12*cm))
        elif s.startswith("## "):
            h1(s[3:])
        elif s.startswith("### "):
            story.append(Paragraph(s[4:], styles["h2"]))
        elif s.startswith(("- ", "* ")):
            bullet(s[2:])
        elif s and s[0].isdigit() and ". " in s[:4]:
            bullet(s)
        elif s:
            body(s)

    # ── Section 6 — ROI ───────────────────────────────────────────────────────
    hr()
    h1("SECTION 6 — ROI ESTIMATION")
    roi_rows = [
        ["Metric", "Value"],
        ["Time saved per week",                  f"{roi['time_saved_per_week']:.1f} hours"],
        ["Efficiency improvement",               f"{roi['efficiency_gain_percent']}%"],
        ["Automation score",                     f"{roi['automation_score']} / 100"],
        ["Annual hours saved",                   f"{roi['annual_hours_saved']:.0f} hours"],
        ["Hours remaining/week (post-opt)",      f"{roi['hours_remaining_per_week']:.1f}h"],
        [f"Annual value (@ ${roi['hourly_value_used']:.0f}/hr)", f"${roi['annual_value_usd']:,.0f}"],
    ]
    roi_t = Table(roi_rows, colWidths=[CONTENT_W*0.58, CONTENT_W*0.42])
    roi_t.setStyle(TableStyle([
        ("BACKGROUND",    (0,0),(-1,0), C_BLUE),
        ("TEXTCOLOR",     (0,0),(-1,0), colors.white),
        ("FONTNAME",      (0,0),(-1,0), "Helvetica-Bold"),
        ("FONTNAME",      (1,1),(1,-1), "Helvetica-Bold"),
        ("FONTSIZE",      (0,0),(-1,-1), 9),
        ("GRID",          (0,0),(-1,-1), 0.3, C_BORDER),
        ("ROWBACKGROUNDS",(0,1),(-1,-1), [colors.white, C_LIGHT]),
        ("TOPPADDING",    (0,0),(-1,-1), 5),
        ("BOTTOMPADDING", (0,0),(-1,-1), 5),
        ("LEFTPADDING",   (0,0),(-1,-1), 8),
    ]))
    story.append(roi_t)
    story.append(Spacer(1, 0.35*cm))

    story.append(Paragraph("Breakdown by Category", styles["h2"]))
    cat_hdr  = [["Category", "Tasks", "Current h/wk", "Hours Saved"]]
    cat_rows = [
        [cat, str(d["tasks"]), f"{d['total_hours']:.1f}h", f"{d['hours_saved']:.1f}h"]
        for cat, d in roi["category_breakdown"].items()
    ]
    cat_t = Table(cat_hdr + cat_rows,
                  colWidths=[CONTENT_W*0.35, CONTENT_W*0.2, CONTENT_W*0.25, CONTENT_W*0.2])
    cat_t.setStyle(TableStyle([
        ("BACKGROUND",    (0,0),(-1,0), C_ACCENT),
        ("TEXTCOLOR",     (0,0),(-1,0), colors.white),
        ("FONTNAME",      (0,0),(-1,0), "Helvetica-Bold"),
        ("FONTSIZE",      (0,0),(-1,-1), 9),
        ("GRID",          (0,0),(-1,-1), 0.3, C_BORDER),
        ("ROWBACKGROUNDS",(0,1),(-1,-1), [colors.white, C_LIGHT]),
        ("TOPPADDING",    (0,0),(-1,-1), 5),
        ("BOTTOMPADDING", (0,0),(-1,-1), 5),
        ("LEFTPADDING",   (0,0),(-1,-1), 8),
    ]))
    story.append(cat_t)
    story.append(Spacer(1, 0.4*cm))

    # ── Final footer note ─────────────────────────────────────────────────────
    hr()
    story.append(Paragraph(
        f"Generated by <b>AI Workflow Auditor</b> — {BRAND_NAME}  ·  "
        f"{LINKEDIN_URL}  ·  {CONTACT_EMAIL}",
        styles["caption"],
    ))

    doc.build(story, onFirstPage=draw_footer, onLaterPages=draw_footer)
    return filepath


# ── Master ───────────────────────────────────────────────────────────────────────

def generate_and_save_reports(analysis: Dict, roi: Dict, ai_content: Dict, output_dir: str) -> Dict:
    ts   = get_timestamp()
    base = f"audit_report_{ts}"
    md   = generate_markdown_report(analysis, roi, ai_content)
    md_p = save_markdown(md, output_dir, f"{base}.md")
    pdf_p= save_pdf(analysis, roi, ai_content, output_dir, f"{base}.pdf")
    return {"markdown": md_p, "pdf": pdf_p, "timestamp": ts}
